sudo: required
# https://docs.travis-ci.com/user/trusty-ci-environment/
dist: xenial
language: python
python:
  - '3.6'
  - '3.7'
env:
  matrix:
    - DB=postgres TEST=pulp
    - DB=mariadb TEST=pulp
    - DB=postgres TEST=docs
matrix:
  exclude:
    - python: '3.6'
      env: DB=postgres TEST=docs
    - python: '3.6'
      env: DB=mariadb TEST=pulp
  fast_finish: true
services:
  - postgresql
  - mariadb
addons:
  apt:
    packages:
      - httpie
      - jq
  # postgres versions provided by el7 RHSCL (lowest supportable version)
  postgresql: '9.6'
  mariadb: '10.3'
before_install: .travis/before_install.sh
install: .travis/install.sh
before_script: .travis/before_script.sh
script: .travis/script.sh
jobs:
  include:
    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        distributions: sdist bdist_wheel
        user: pulp
        password:
          secure: "nbn1RGf6CEObxurenvbBrS/NzeVqsD2kcYxqLazfqYcp4rBbAL3y8LZDalrNmKr4ge0Byj7tiRD84vvhNf2rcHLW2g7zJ/Av3DuIdZAYtsbr2OO2IiaNzj3RphFHs3GNF0W/C5WjlS8GO+0LKQcgWVKka2oyftiOWNJd3Zh37FPxea9kcoTWBw6lJA8PdQgMBm7qY3IsDI6kYQex8sXbY8kQuhNDx/va4BoYs0sRSsq6cWmKfia3zFO0Mi2Z3Aprj2C8TcogWL0gk2rT49TNt+jA9WkIRBFGn5EF3LGlACOTC2EEhGayt4KiCO9lCPMHMVuvwYxHASR8CFP6Db7hAzAy1t6A84JE3TEsoP5jkt/W1/taqwr+TxlCiCNp21C9+68clthQ+CFUmvAvOywI/3DHWsIE2BS1Zzr57qvQdCz2polwY/c3su/k7LJxuCf1RjLACpDV4dk8/swUhduptmL5Bz6lMEP/u1ZkfUW7GwCNfD12UrFD2wYkyyKy54UDNR/4AjE/zXTkcJuCEFyN1uTIiRmQwgII09QpuV08hDedrRMg38iF17AZ1ZuNEcxYf6XtYjUtkTcHNe7zm5453YZ/YrHtZRnMjtQX2+dv0N2xLBRsbHw4cfp5aYhnc9QvJDoFgHFP6NL6RCtps01Tl7gmcYL99Rju9yFHRICxlI4="
        on:
          tags: true
      if: tag IS present
    - stage: publish-beta-docs
      script: bash .travis/publish_docs.sh beta
      env:
        - DB=postgres
        - TEST=docs
      if: tag IS present
    - stage: publish-nightly-docs
      script: bash .travis/publish_docs.sh nightly
      env:
        - DB=postgres
        - TEST=docs
      if: type != pull_request
